# Generated by Django 6.0.3 on 2026-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='grupo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_control',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(default='cliente', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='casillero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='edificio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
