# Generated by Django 6.0.3 on 2026-04-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_rol_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_verificado',
            field=models.BooleanField(default=True),
        ),
    ]
