# Generated by Django 6.0.3 on 2026-04-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_email_verificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='foto',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono_contacto',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_externa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
